# Generated by Django 5.0.6 on 2024-10-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
    ]
